image: docker:latest


stages:
  - build
  - deploy

variables:
  APP: xijia
  IMAGE_NAME: ${APP}_back:${CI_COMMIT_REF_NAME}
  DB_PASSWORD: chaozi
  APP_FULL: ${APP}_${CI_COMMIT_REF_NAME}
  PORT: 201
  DOCS_URI: "http://139.196.85.124:20101/apidocs.json"


build:
  stage: build
  retry: 2
  tags:
    - xijia
  script:
    - docker build -t ${IMAGE_NAME} .


## 通过gitlab创建 数据库 redis
deploy:
  image: tmaier/docker-compose
  stage: deploy
  retry: 2
  tags:
    - xijia
  script:
    - docker-compose up -d
