image: docker:latest


stages:
  #  - build
  - deploy

variables:
  APP: template
  API_IMAGE_NAME: ${APP}_api:${CI_COMMIT_REF_NAME}
  BACK_IMAGE_NAME: ${APP}_back:${CI_COMMIT_REF_NAME}
  APP_FULL: ${APP}_${CI_COMMIT_REF_NAME}
  DB_USER: chaozi
  DB_PASSWORD: Dream001$
  DB_HOST: db
  DB_NAME: chaozi
  DOCS_URI: "http://124.221.131.183:20101/apidocs.json"


#build:
#  stage: build
#  retry: 2
#  tags:
#    - chaozi
#  script:
#    - docker build -t ${API_IMAGE_NAME} .

deploy:
  image: tmaier/docker-compose
  stage: deploy
  retry: 2
  tags:
    - chaozi
  variables:
    PORT: 201
  script:
    #    - mkdir ${APP_FULL} && cp ./docker-compose.yml ./${APP_FULL} && cd ${APP_FULL}
    - ls
    - ls ./amis
    - docker-compose up -d
    - docker-compose restart nginx