image: docker:latest


stages:
  - build
  - deploy

variables:
  APP: template
  IMAGE_NAME: ${APP}_api:${CI_COMMIT_REF_NAME}
  APP_FULL: ${APP}_${CI_COMMIT_REF_NAME}
  DB_USER: chaozi
  DB_PASSWORD: sdad12sac$!addQQ
  DB_HOST: db
  DB_NAME: chaozi
  DOCS_URI: "http://124.221.131.183:20101/apidocs.json"


build:
  stage: build
  retry: 2
  tags:
    - template
  script:
    - docker build -t ${IMAGE_NAME} .

deploy:
  image: tmaier/docker-compose
  stage: deploy
  retry: 2
  tags:
    - template
  variables:
    PORT: 201
  script:
    - mkdir ${APP_FULL} && cp ./docker-compose.yml ./${APP_FULL} && cd ${APP_FULL}
    - docker-compose up -d
    - docker-compose restart nginx