version: '3.1'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /data
    volumes:
      - "${PG_DATA}:/data"
    ports:
      - "${PG_PORT}:5432"
    expose:
      - "5432"
    restart: always
    container_name: ${NET}_db
    networks:
      - my_network

  redis:
    image: redis:6
    restart: always
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    container_name: ${NET}_redis
    networks:
      - my_network

networks:
  my_network:
    external:
      name: ${NET}