"""empty message

Revision ID: 231e522ba12d
Revises: e77deab7dc4e
Create Date: 2022-01-21 22:11:00.327371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '231e522ba12d'
down_revision = 'e77deab7dc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'author', ['id'])
    op.add_column('book', sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'book', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_column('book', 'extend')
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'extend')
    # ### end Alembic commands ###
